version: '3'

services:
  api:
    image: negrero/gameionicpwaapi:0.0.1  
    networks:
      - proxy
    
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - "node.role == manager"
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
      - traefik.enable=true
      - traefik.http.routers.game-ionic-pwa-api-secured.entrypoints=web-secured
      - traefik.http.routers.game-ionic-pwa-api-secured.rule=Host(`game-ionic-pwa-api.valdepeace.com`)
      - traefik.http.routers.game-ionic-pwa-api-secured.tls.certresolver=mytlschallenge
      - traefik.http.routers.game-ionic-pwa-api.entrypoints=web
      - traefik.http.routers.game-ionic-pwa-api.priority=1
      - traefik.http.routers.game-ionic-pwa-api.rule=Host(`game-ionic-pwa-api.valdepeace.com`)
      - traefik.http.services.game-ionic-pwa-api.loadbalancer.server.port=3000
volumes:
  gamedb_data:
networks:
  proxy:
    external: true
